"""add_generations_table

Revision ID: 1629ce053adf
Revises: a938765d13b2
Create Date: 2026-02-18 03:30:45.873477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1629ce053adf'
down_revision: Union[str, Sequence[str], None] = 'a938765d13b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cut_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('cfg_scale', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('invokeai_reference_image_name', sa.String(length=500), nullable=True),
    sa.Column('invokeai_generated_image_name', sa.String(length=500), nullable=True),
    sa.Column('actual_seed', sa.Integer(), nullable=True),
    sa.Column('reference_frame_path', sa.String(length=1000), nullable=True),
    sa.Column('output_image_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cut_id'], ['cuts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generations_cut_id', 'generations', ['cut_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generations_cut_id', table_name='generations')
    op.drop_table('generations')
    # ### end Alembic commands ###
