"""

Revision ID: 40e6d0b58ae1
Revises: f7c1b2e4a8d9
Create Date: 2026-04-04 01:22:09.345985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40e6d0b58ae1'
down_revision: Union[str, Sequence[str], None] = 'f7c1b2e4a8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_config_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=50), nullable=False),
    sa.Column('old_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_config_audits_id'), 'service_config_audits', ['id'], unique=False)
    op.create_index(op.f('ix_service_config_audits_service_key'), 'service_config_audits', ['service_key'], unique=False)
    op.create_table('service_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_configs_id'), 'service_configs', ['id'], unique=False)
    op.create_index(op.f('ix_service_configs_service_key'), 'service_configs', ['service_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_configs_service_key'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_id'), table_name='service_configs')
    op.drop_table('service_configs')
    op.drop_index(op.f('ix_service_config_audits_service_key'), table_name='service_config_audits')
    op.drop_index(op.f('ix_service_config_audits_id'), table_name='service_config_audits')
    op.drop_table('service_config_audits')
    # ### end Alembic commands ###
