"""add takes table

Revision ID: a9439f22c9d3
Revises: 123738526a26
Create Date: 2026-02-18 05:09:41.103381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9439f22c9d3'
down_revision: Union[str, Sequence[str], None] = '123738526a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('comfyui_prompt_id', sa.String(length=500), nullable=True),
    sa.Column('actual_seed', sa.BigInteger(), nullable=True),
    sa.Column('output_video_path', sa.String(length=1000), nullable=True),
    sa.Column('canny_video_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_takes_generation_id', 'takes', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_takes_generation_id', table_name='takes')
    op.drop_table('takes')
    # ### end Alembic commands ###
